Document: lmt
Title: Debian lmt Manual
Author: <insert document author here>
Abstract: This manual describes what lmt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmt/lmt.sgml.gz

Format: postscript
Files: /usr/share/doc/lmt/lmt.ps.gz

Format: text
Files: /usr/share/doc/lmt/lmt.text.gz

Format: HTML
Index: /usr/share/doc/lmt/html/index.html
Files: /usr/share/doc/lmt/html/*.html
