Document: lmt-gui
Title: Debian lmt-gui Manual
Author: <insert document author here>
Abstract: This manual describes what lmt-gui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmt-gui/lmt-gui.sgml.gz

Format: postscript
Files: /usr/share/doc/lmt-gui/lmt-gui.ps.gz

Format: text
Files: /usr/share/doc/lmt-gui/lmt-gui.text.gz

Format: HTML
Index: /usr/share/doc/lmt-gui/html/index.html
Files: /usr/share/doc/lmt-gui/html/*.html
