Document: lmt-repo-tools
Title: Debian lmt-repo-tools Manual
Author: <insert document author here>
Abstract: This manual describes what lmt-repo-tools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lmt-repo-tools/lmt-repo-tools.sgml.gz

Format: postscript
Files: /usr/share/doc/lmt-repo-tools/lmt-repo-tools.ps.gz

Format: text
Files: /usr/share/doc/lmt-repo-tools/lmt-repo-tools.text.gz

Format: HTML
Index: /usr/share/doc/lmt-repo-tools/html/index.html
Files: /usr/share/doc/lmt-repo-tools/html/*.html
